### ISSUE TITLE
感觉在设置重复相加这块是不是有点问题。。。。

### ISSUE THREAD

**Issue by luffycjf** [abcfy2/python-2048#6]
[0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 4]
假设初始数组是这样的。那么第一次向上划完，程序输出的是
[0, 0, 2, 4, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 0]
最下面的两个4并没有加，正常不应该是这样[0, 0, 2, 4, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0]吗？
刚来学习python，求大神轻喷

**Comment by abcfy2** [comment]
最早我的设计跟你一样的，后来我实际玩了下2048的游戏，这种情况原始的游戏算法是不会叠加合并的，于是我的逻辑算法就改了，合并过的格子会做一个标记，有标记的数字不会叠加。

**Comment by abcfy2** [comment]
哦，我明白你说的意思了，这里应该是逻辑的BUG。我以为你说的是:

```
0 0 0 2
0 0 0 2
0 0 0 2
0 0 0 2
```

这种情况在原始游戏中会被合并成:
```
0 0 0 4
0 0 0 4
0 0 0 0
0 0 0 0
```
当时为了做这个逻辑加了个mergedList，看来这里判断有BUG，抽时间重新设计下这里的算法吧，毕竟是三年前自己刚学python的代码，有些逻辑想不太清楚了，欢迎递交pull request。

**Comment by abcfy2** [comment]
Merged, thanks.
